Dz1
NikitaBarshchevskii/2024-2-VK-EDU-Frontend-N-Barshchevskii pull request #1
Opened 2024-09-22 23:23 UTC by NikitaBarshchevskii

# Домашнее задание №1

Прошу @martinkomitsky, @haseprogram, @kgrechin или @ivan-bir проверить его.

Что было сделано:
* Реализация функций в файлах `convertBytesToHuman.js`, `correctSentence.js`, `nonUniqueElements.js`;
* Написание тестов на функцию `convertBytesToHuman`;
* Написание дополнительных тестов для `correctSentence`, `nonUniqueElements`;

2024-09-26 14:56 UTC, Ivan-Bir requested changes

2024-09-26 14:56 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +/*
Привет! Добро пожаловать на курс
Я буду твоим ментором и буду рад ответить на любые вопросы по курсу

2024-09-26 14:56 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +  //Converting bytes with each iteration
Слишком очевидно, чтобы пояснять

2024-09-26 14:56 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +  const str = bytes + " " + units[counter];
Лучшие использовать шаблонные строки `${var1} ${var2}`, это более гибко и безопасно

2024-09-26 14:56 UTC, Ivan-Bir commented on convertBytesToHuman.test.js
> +// другая группа проверок
Лишний комент

2024-09-26 14:56 UTC, Ivan-Bir commented on correctSentence.js
> +  //Getting rid of possible whitespaces
Не надо пояснять каждую строчку коментом. Коменты используем только чтобы объяснить что-то неоднозначное, сомнительное или сложное. Здесь и далее

2024-09-26 14:56 UTC, Ivan-Bir commented on correctSentence.js
> +    text = text[0].toUpperCase() + text.slice(1);
Шаблонные строки, помним. Здесь и далее

2024-09-26 14:56 UTC, Ivan-Bir commented on correctSentence.test.js
> +  expect(correctSentence("")).toBe(".")
Это не то поведение, которое ожидается. Более ожидаемым будет пустая строка

2024-09-26 14:56 UTC, Ivan-Bir commented on nonUniqueElements.js
> +    if(encounteredElements.get(element) > 1){
Нет пробела перед фигурной скобкой. Чтобы не отвлекаться на ошибки форматирования, можно для vscode использовать Prettier

2024-09-26 14:56 UTC, Ivan-Bir commented on nonUniqueElements.js
> +  return result
Проверь здесь и везде ;

2024-09-26 14:56 UTC, Ivan-Bir commented on nonUniqueElements.js
> +  data.forEach(element => {
Даже если это параметр стрелочной функции, то его принято оборачивать в скобки

2024-09-26 14:56 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +  let counter = 0;
Переменную объявляем как можно ближе к месту её использования

2024-09-28 09:50 UTC, Ivan-Bir approved these changes

2024-09-28 09:51 UTC, Ivan-Bir commented
Не придраться. Апрув

2024-09-29 13:46 UTC, merged

2024-09-29 13:46 UTC, martinkomitsky commented
12!